type GuildMissionsServerKey = keyof Omit<typeof GuildMissionServer, 'parse'>;

export function parse(bdoServerName: string) {
    return GuildMissionServer[bdoServerName as GuildMissionsServerKey];
}

export enum GuildMissionServer {
    ars1 = 'NA_Arsha (PVP)',
    bal1 = 'NA_Balenos1',
    bal2 = 'NA_Balenos2',
    bal3 = 'NA_Balenos3',
    bal4 = 'NA_Balenos4',
    bal5 = 'NA_Balenos5',
    bal6 = 'NA_Balenos6',
    cal1 = 'NA_Calpheon1',
    cal2 = 'NA_Calpheon2',
    cal3 = 'NA_Calpheon3',
    cal4 = 'NA_Calpheon4',
    cal5 = 'NA_Calpheon5',
    cal6 = 'NA_Calpheon6',
    kam1 = 'NA_Kamasylvia1',
    kam2 = 'NA_Kamasylvia2',
    kam3 = 'NA_Kamasylvia3',
    kam4 = 'NA_Kamasylvia4',
    kam5 = 'NA_Kamasylvia5',
    kam6 = 'NA_Kamasylvia6',
    med1 = 'NA_Mediah1',
    med2 = 'NA_Mediah2',
    med3 = 'NA_Mediah3',
    med4 = 'NA_Mediah4',
    med5 = 'NA_Mediah5',
    med6 = 'NA_Mediah6',
    olv1 = 'NA_New Olvia1',
    olv2 = 'NA_New Olvia2',
    olv3 = 'NA_New Olvia3',
    olv4 = 'NA_New Olvia4',
    rul1 = 'NA_Rulupee1',
    rul2 = 'NA_Rulupee2',
    rul3 = 'NA_Rulupee3',
    rul4 = 'NA_Rulupee4',
    rul5 = 'NA_Rulupee5',
    rul6 = 'NA_Rulupee6',
    rulu1 = 'NA_Rulupee1',
    rulu2 = 'NA_Rulupee2',
    rulu3 = 'NA_Rulupee3',
    rulu4 = 'NA_Rulupee4',
    rulu5 = 'NA_Rulupee5',
    rulu6 = 'NA_Rulupee6',
    sea1 = 'NA_Season1 (Novice Only)',
    sea2 = 'NA_Season2',
    sea3 = 'NA_Season3',
    sea4 = 'NA_Season4',
    sea5 = 'NA_Season (PVP)',
    ser1 = 'NA_Serendia1',
    ser2 = 'NA_Serendia2',
    ser3 = 'NA_Serendia3',
    ser4 = 'NA_Serendia4',
    ser5 = 'NA_Serendia5',
    ser6 = 'NA_Serendia6',
    val1 = 'NA_Valencia1',
    val2 = 'NA_Valencia2',
    val3 = 'NA_Valencia3',
    val4 = 'NA_Valencia4',
    val5 = 'NA_Valencia5',
    val6 = 'NA_Valencia6',
}